### ISSUE TITLE
[Issue] 2FA Code prevents login

### ISSUE THREAD

**Issue by JoanJuan10** [hawolt/custom-league-client#1]
I have tried login into my account that has 2FA with a code sent to my email and the login screen just stays there, waiting for nothing to happen because it needs the code sent to my email.

[https://i.imgur.com/ulJ0Fv4.png](https://i.imgur.com/ulJ0Fv4.png)

**Comment by hawolt** [comment]
should be fixed with https://github.com/hawolt/custom-league-client/commit/7f8557f6c1fcc1c2725378ec9b62955fe7b5cebe
