### ISSUE TITLE
[BUG] StoreButtons appearing above the Chat Window if unlucky resized or randomly on hover

### ISSUE THREAD

**Issue by slyk26** [hawolt/custom-league-client#11]
**Describe the bug**
When you open chat window while having the Store UI in the background you will sometimes see a storebutton inside the chat 

**To Reproduce**
Account Region: Uganda
1. Go to 'Store'
2. Click on 'a friend' (chat window opens)
3. Try to hover above a StoreButton to buy a champion which is behind the Chat Window
4. See error (Store Button above the Chat window)

DOESNT WORK EVERYTIME ... what works everytime tho is:

1. Go to 'Store'
2. Click on 'a friend' (chat window opens)
3. Resize window so that a StoreButton is slightly peeking out of the chat window (on the left side of the window; see screenshot below)
4. See error (Store Button above the Chat window)

**Expected behavior**
The Store Button doesnt appear out of nowhere

**Screenshots**

![image](https://github.com/hawolt/custom-league-client/assets/102811034/6c6b1912-5b11-4f53-a479-6fec975db9a8)

![image](https://github.com/hawolt/custom-league-client/assets/102811034/2180593f-61b9-4715-9dd5-6e95086c9ca5)

**Comment by hawolt** [comment]
fixed with commit 395fa93e3e26ffb704ebe77d756e31f8310c0392 which is currently available in alpha-dev pre-release 1.03
