### ISSUE TITLE
[BUG] Initialising friendlist still doesnt work

### ISSUE THREAD

**Issue by xthesebx** [hawolt/custom-league-client#114]
**Describe the bug**
initialising friendlist only shows correct status of 3-10 people

**To Reproduce**
Account Region:
EUW

Have a lot of friends (also online etc.)
Start client
some friends show correctly, some dont

**Expected behavior**
every player gets initialised with correct presence

**Screenshots**
![image](https://github.com/hawolt/custom-league-client/assets/13334995/f518a1a6-724c-48c0-b14c-429f54f5f638)

**Additional context**

**Comment by hawolt** [comment]
should finally be fixed with #125 &  #127 sorting and proper status are not included in these
