### ISSUE TITLE
[BUG] An attempt to play any audio through the client ends with an ERROR

### ISSUE THREAD

**Issue by rdelynali** [hawolt/custom-league-client#12]
**Describe the bug**
If the user tries to use any function of the program that should play sound then nothing will be played.

**To Reproduce**
Account Region: EUW
1. Open client.
2. Try to "generate" sound by changing status/opening store etc.

**Expected behavior**
Play sound

**Additional context**
Examples of error:
[ERROR] com.hawolt.util.AudioEngine::lambda$play$1 Failed to play air_button_press_1.wav
[ERROR] com.hawolt.util.AudioEngine::lambda$play$1 Failed to play openstore.wav
[ERROR] com.hawolt.util.AudioEngine::lambda$play$1 Failed to play matchmakingqueued.wav

**Comment by hawolt** [comment]
audio files are not supplied in this repository due to obvious copyright issues, please ignore these
