### ISSUE TITLE
[REQUEST] Champion image desaturation after ban

### ISSUE THREAD

**Issue by rdelynali** [hawolt/custom-league-client#14]
**Is your feature request related to a problem? Please describe.**
Actually no

**Describe the solution you'd like**
If a champion is banned, it should be desaturated (become grey) and it should not be possible to click on such a champion

**Describe alternatives you've considered**
Removing the champion from the selection completely, but this can be confusing for the user, so the first solution seems better.

**Comment by hawolt** [comment]
just added this, will be on dev later today when I push the changes
