### ISSUE TITLE
[BUG] Poor showing of selected summoners and faulty selection of smite

### ISSUE THREAD

**Issue by rdelynali** [hawolt/custom-league-client#16]
**Describe the bug**
The summoner selection is very buggy, it is not possible to select smite (sometimes the summoner list bugs up without displaying any value). Additionally, the name of ignite is not displayed, but it is possible to select it (look at imgur). Summoners often do not display as they should (as they are set in the interface, look at imgur).

**To Reproduce**
Account Region: EUW
1. Open client
2. Start any queue
3. Get into lobby
4. Try to change summoners/change to smite
**Expected behavior**
The client should allow the selection of all summoners (according to mode). When the user selects the same summoner from the first list and then from the second list, the summoners should be swapped. (For example, I select flash from the first list, in the second list I have heal, then when I select flash in the second list, heal should jump to the first list. This behaviour is the default in the original client.
**Screenshots**
[imgur](https://imgur.com/a/N1Zltk8)

**Comment by hawolt** [comment]
should be fixed with the last alpha-dev pre release
