### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ExcaroX** [hawolt/custom-league-client#164]
**Describe the bug**
Client not starting

**To Reproduce**
Account Region:EUW

When i open it for first time was working, after i put my user/pw and click login the client redirect me to the browser for captcha and after that the client freeze. I close it and tried to open it again but didnt work.

**Expected behavior**

**Screenshots**
![image](https://github.com/hawolt/custom-league-client/assets/125036586/24f234aa-45d8-45ed-97ae-14bd1b8949be)

**Additional context**

**Comment by xthesebx** [comment]
fixed on dev for rn: delete the swift-rift directory in your homedir

**Comment by ExcaroX** [comment]
work thanks 👍
