### ISSUE TITLE
[BUG] Friend list won't show up

### ISSUE THREAD

**Issue by ragingmarcel** [hawolt/custom-league-client#17]
**Describe the bug**
The friendlist won't display being left empty.

**To Reproduce**
Account Region: SEA
Logging into the Swift Rift Client

**Expected behavior**
The friendlist would be left blank.

**Screenshots**
![javaw_ceQk3O94MB](https://github.com/hawolt/custom-league-client/assets/41146096/5ea82cb0-9367-45fe-81ae-a9d572f6cb1f)

**Comment by rdelynali** [comment]
try restarting your client, usually two restarts work and the list loads, however when you try to log in from a different account the problem will persist (on the other account)

**Comment by hawolt** [comment]
should be fixed with the most recent commit & release https://github.com/hawolt/custom-league-client/commit/3fe4c5462ee1908757dffbfb6c03665b8bbf985d
