### ISSUE TITLE
[BUG] Owned skins with special characters appear as buyable in shop

### ISSUE THREAD

**Issue by zRevenger** [hawolt/custom-league-client#184]
**Describe the bug**
Looking for owned skins in the shop that contain special characters (mainly project skins with their Project: Champion format) displays the skin even when owned.

**To Reproduce**
Account Region: ANY

1. Go to Shop
2. Search for an owned project skin

**Expected behavior**
As no other owned skin is displayed, expected behaviour is to not display the owned skin

**Screenshots**
Swift Rift shop:
![image](https://github.com/hawolt/custom-league-client/assets/56997948/acfe9441-63b0-4d74-9501-8bf3c4dcb498)
Lol client collection:
![image](https://github.com/hawolt/custom-league-client/assets/56997948/3be498ac-d8f1-4631-b08c-50e410b34d25)

**Comment by hawolt** [comment]
fixed on latest dev branch for now
