### ISSUE TITLE
[BUG] Skin variances not working properly in shop

### ISSUE THREAD

**Issue by Lett4s** [hawolt/custom-league-client#195]
**Describe the bug**
Skin variances show wrong price when owning one of the variance and are not buyable.

**To Reproduce**
Account Region:

1. Own one skin variance (e.g. Dark Cosmic Lux)
2. Open shop and search for Cosmic Lux
3. Skin shows up with price 1820RP and is not buyable

**Expected behavior**
- When owning one of the skins, the other should shown correct price (e.g. 1001RP)
- Skin should be buyable

**Additional context**
Going to look into it tomorrow

**Comment by hawolt** [comment]
fixed on latest dev branch for now
