### ISSUE TITLE
[REQUEST] Queue buttons QoL changes

### ISSUE THREAD

**Issue by rdelynali** [hawolt/custom-league-client#24]
**Describe the solution you'd like**
By default, the stop queue button should be non-clickable, and its color should be changed (to gray or something). It should be clickable only when the player is in the queue (then the queue start button should not be clickable).

**A thing that can also be done**
After changing the mode during the queue (for example, from draft to ranked flex), all buttons should be available, the stop button will stop the current queue (for example, draft), and the start button will start the selected queue (for example, flex).

**Comment by stdbasti** [comment]
will do
