### ISSUE TITLE
[REQUEST] Prioritize client window during queue accept and Ban/Pick phase

### ISSUE THREAD

**Issue by rdelynali** [hawolt/custom-league-client#25]
**Describe the solution you'd like**
After the queue accept window pops up, the client should appear on top of other applications. Likewise with a ban/pick. A behavior known from the original client, but is very useful as a lot of players alt+tab during queue/champion select.

**Comment by Danielryb** [comment]
This should be optional or at least work in a way which makes it appear on top without taking priority. Official league client doesn't disable the priority until you click on the client directly, which makes it annoying and confusing when you want to ignore it for a moment and quickly finish your previous activity.

**Comment by rdelynali** [comment]
> This should be optional or at least work in a way which makes it appear on top without taking priority. Official league client doesn't disable the priority until you click on the client directly, which makes it annoying and confusing when you want to ignore it for a moment and quickly finish your previous activity.

totally agree

**Comment by rdelynali** [comment]
but as long as there is no sound to indicate that a match has been found then, imo, this should be the default option to somehow notify the user of the game

**Comment by hawolt** [comment]
added on dev for now
