### ISSUE TITLE
[REQUEST] Display low prio queue error

### ISSUE THREAD

**Issue by rdelynali** [hawolt/custom-league-client#26]
**Describe the solution you'd like**
Display an error when a player tries to join a queue when they have a low priority queue/show the timer of that queue. Similarly with restricted queue after lobby dodge.

**Comment by hawolt** [comment]
fixed in latest alpha-dev pre-release 1.03 with commit https://github.com/hawolt/custom-league-client/commit/16694e852d6a5a118210e6ec676e7a1f62ece38c
