### ISSUE TITLE
[BUG] No Electrocute rune

### ISSUE THREAD

**Issue by Safsalim** [hawolt/custom-league-client#27]
The Electrocute rune doesn't show up in runes
https://i.imgur.com/xfvu9Kr.png

**Comment by pabelito04** [comment]
More info needed https://imgur.com/a/ap4m2l8

**Comment by hawolt** [comment]
probably a network issue, if a resource fails to load it will not retry to load it again
not looking into this until I have local files which should not fail to load ever, will leave this issue open though

**Comment by Safsalim** [comment]
A simple reset fixed it I was too quick to post the issue sorry :/

**Comment by hawolt** [comment]
this can happen anytime due to network errors, I am going to close this and any similar future issues like this - worst case it will be fixed with one restart as of now
