### ISSUE TITLE
[REQUEST] Lobby/draft QoL changes

### ISSUE THREAD

**Issue by rdelynali** [hawolt/custom-league-client#28]
**Describe the solution you'd like**
When the draft starts, the window should switch from the queue window to the draft window. If the lobby is dodged then the window should return to queue (only if the player is in the draft window, we don't want a situation where the player tries to buy something during the draft and it moves him back to the queue window). 
The chat should be cleared after dodge (if we are the one who dodged then the queue timer should reset also). The selection timer (animation for banning/picking) should also reset.

**Comment by hawolt** [comment]
this should be current behaviour to some degree
