### ISSUE TITLE
Accept/decline queue pop up doesnt appear after someone doesnt accept the first one

### ISSUE THREAD

**Issue by Cral3r** [hawolt/custom-league-client#3]
Accept/decline queue pop up doesnt appear after someone doesnt accept the first one

**Comment by hawolt** [comment]
will be looking at this later today, thanks for letting me know

**Comment by hawolt** [comment]
should be fixed with the most recent commit & release https://github.com/hawolt/custom-league-client/commit/3fe4c5462ee1908757dffbfb6c03665b8bbf985d
