### ISSUE TITLE
[BUG] Not able to queue up and play on LAS/LAN/BR 

### ISSUE THREAD

**Issue by guisaliba** [hawolt/custom-league-client#31]
Tried to play a game at BR region but not able to enter queue, error thrown on terminal:  `Exception in thread "AWT-EventQueue-0" org.json.JSONException: JSONObject["parties"] not found.` Not even sure if this is a bug.. it is just not working right now, same for LAS and LAN regions. Opening this issue as told me to at Hawolt's Discord server.

**Comment by hawolt** [comment]
should be fixed with the last alpha-dev pre release
