### ISSUE TITLE
[REQUEST] QOL improvements in the client

### ISSUE THREAD

**Issue by slyk26** [hawolt/custom-league-client#46]
**Is your feature request related to a problem? Please describe.**
No it's not ... it's several QOL improvements targeted for people who want to help but don't know where to start.

**Describe the solution you'd like**

* darkmode/ theme for the client (setting darker bg, changing defaults, maybe even adding a custom look and feel)
* adding championnames to the champions in the Shop (bottom center like in the vanilla client)
* better purchase flow in the shop: click item in shop -> popup to confirm purchase (similar like in vanilla client)
* generally refactoring ui code (maybe discouraged because merge conflicts)
* formatting UI Buttons (Store, Play, ...) and grouping the Gamemodes in the PLAY JPanel

**Comment by hawolt** [comment]
update: most of this is implemented - currently missing popups to confirm purchases rather than instantly firing it

**Comment by hawolt** [comment]
included in next dev commit
