### ISSUE TITLE
[BUG] Champion select not resetting properly when random dodges

### ISSUE THREAD

**Issue by Karakazz** [hawolt/custom-league-client#56]
**Describe the bug**
The champselect is filled with prior picks/bans/pick order when any of the other 4 players dodge the game.

**To Reproduce**
Account Region:EUW

1. Enter champion select.
2. Let someone else dodge.
3. Verify your champion selection, noting that everything remains as it was from the previous champion selection.
4. Enter a new champion selection.
5. Observe that the prior champion selection persists.

**Expected behavior**
The champion select resets as if you've dodged it yourself.

**Screenshots**
(https://imgur.com/a/xlW1Dx5)
See picked champions as well as completed bans while in ban phase, again.

**Comment by hawolt** [comment]
fixed with #113
