### ISSUE TITLE
[BUG] Queueing TFT freezes the client

### ISSUE THREAD

**Issue by Karakazz** [hawolt/custom-league-client#57]
**Describe the bug**
When starting a TFT queue the client freezes for 2-3 seconds and no other actions are possible. 

The client in the current dev build also freezes when you try to open a lobby but that seems to be fixed in PR #55 

**To Reproduce**
Account Region: euw
1. Click Play
2. Click on TFT-RANKED-TB or any other queue and notice freeze (fixed in #55)
3. Click start queue and notice freeze again. 

**Expected behavior**
No freeze when clicking start queue

**Comment by xthesebx** [comment]
Think I already know why, will look into it

**Comment by xthesebx** [comment]
fixed on dev

**Comment by hawolt** [comment]
release with fix is published
