### ISSUE TITLE
Unknown Error during login

### ISSUE THREAD

**Issue by HeroRickyGAMES** [hawolt/custom-league-client#67]
When I try to login using this custom client this appears: Unknown Error during login
Region: BR.
I already have everything installed, including intellij

**Comment by xthesebx** [comment]
what release/branch are you using?

**Comment by zRevenger** [comment]
This is happening on the main league client too and is most likely not related to this repository

**Comment by hawolt** [comment]
could have been both 2FA or using an outdated client, both should work properly now on dev branch
will close this issue once I publish a new release

**Comment by HeroRickyGAMES** [comment]
I tested it on my main and tested it on my secondary and it gave the same problem.
My main has 2FA, but the secondary does not.

**Comment by hawolt** [comment]
should be resolved, fixed in latest release - his was caused by an invalid request
