### ISSUE TITLE
[BUG] Doesnt Show initial Online status

### ISSUE THREAD

**Issue by xthesebx** [hawolt/custom-league-client#69]
**Describe the bug**
Shows online status only if person changed status to online while client is running (e.g. coming on, game ends etc.)

**To Reproduce**
Account Region:
EUW
have someone in friendlist online
start hawolt client
friend shows as offline

**Expected behavior**
friend shows as online

**Screenshots**

**Additional context**

**Comment by hawolt** [comment]
see #114
