### ISSUE TITLE
[BUG] Friendlist

### ISSUE THREAD

**Issue by xthesebx** [hawolt/custom-league-client#78]
**Describe the bug**
Friendlist is not sorting after searching + if presence changes the elements dont refresh and sometimes just disappear until you hover over em

**To Reproduce**
Account Region: should be every region
search
not sorted anymore
for the other problem just stay online and change presence with other acc or wait till someone changes presence

**Expected behavior**
friends should be sorted + friends shouldnt "disappear" and refresh their presence

**Comment by 08AHAD** [comment]
I want to work on this issue.

**Comment by xthesebx** [comment]
btw. its about friendlist not chat (mb) + it doesnt even work with scrolling anymore etc.
completely broken

**Comment by hawolt** [comment]
see #114
