### ISSUE TITLE
[BUG] future bug: client shows wrong changelog if newer version of client exists

### ISSUE THREAD

**Issue by slyk26** [hawolt/custom-league-client#83]
**Describe the bug**
 if your client is outdated it will always show newest changelog insteadf of  changelog of the actual version

**To Reproduce**
1. have a client with version alpha 1.05 while a newer release is out
2. start client

**Expected behavior**
client fetches always latest release instead of the release info of the actual versoin

**Screenshots**

**Additional context**
move client version to static configs class (which has to be updated manually then) and fetch the correct release changelog from github

**Comment by Lett4s** [comment]
fixed starting alpha-1.10
