### ISSUE TITLE
[BUG] - Rune selection page issue

### ISSUE THREAD

**Issue by zRevenger** [hawolt/custom-league-client#88]
**Describe the bug**
When pressing the runes button it doesn't show anything, but if I click where some of the runes should be, that part of the rune page starts showing, this forces the rune page until you select the store.

**To Reproduce**
Account Region: EUW

1. Click on 'Runes'

**Expected behavior**
Rune page shows, I edit, save, get back to what I was doing

**Screenshots**
https://imgur.com/uN5qv74

**Comment by hawolt** [comment]
fixed on dev branch
