### ISSUE TITLE
Sorting Friends Depending on Online status

### ISSUE THREAD

**Issue by stdbasti** [hawolt/custom-league-client#9]
Just make online friends show at the top. Maybe even add grouping for certain online status so you can filter the offline ones. 
Its just really annoying having to search people in your friendlist because they are shown at the bottom even if they are online.

**Comment by hawolt** [comment]
should now be a working feature with the most recent commit & release https://github.com/hawolt/custom-league-client/commit/3fe4c5462ee1908757dffbfb6c03665b8bbf985d
